-- ================================================================
-- seed_catalog_v5.sql — physics-simulations.org (127 sims!)
-- Free interactive HTML5 simulations. Top picks per category.
-- ================================================================
-- author_tenant_name va explícito en cada fila: la columna es NOT NULL
-- SIN DEFAULT y con STRICT_TRANS_TABLES (producción: MariaDB 11.8) el
-- INSERT entero aborta con ERROR 1364 si se omite. Valor '' = el mismo
-- que escribe la app para recursos de comunidad (api/resources.php).

-- ── Wave Phenomena ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Doppler Effect Simulation','Visualize the Doppler effect with a moving source. See wavefronts compress and stretch.','https://physics-simulations.org/simulation/doppler-effect/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/doppler-effect/','Physics Simulations',MD5('psim-doppler'),0,1,'iarepo','','approved'),
('Double Slit Experiment','Interactive Young\'s double slit experiment showing interference patterns.','https://physics-simulations.org/simulation/double-slit-experiment/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/double-slit-experiment/','Physics Simulations',MD5('psim-double-slit'),0,1,'iarepo','','approved'),
('Standing Waves Simulation','Create standing wave patterns with adjustable frequency and boundary conditions.','https://physics-simulations.org/simulation/standing-waves/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/standing-waves/','Physics Simulations',MD5('psim-standing-waves'),0,1,'iarepo','','approved'),
('Ripple Tank Simulation','2D wave phenomena — interference, diffraction, and reflection.','https://physics-simulations.org/simulation/ripple-tank/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/ripple-tank/','Physics Simulations',MD5('psim-ripple-tank'),0,1,'iarepo','','approved'),
('Fourier Synthesis','Build complex waveforms by adding harmonics. See Fourier decomposition.','https://physics-simulations.org/simulation/fourier-synthesis/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/fourier-synthesis/','Physics Simulations',MD5('psim-fourier'),0,1,'iarepo','','approved'),
('Chladni Patterns','Visualize 2D vibration patterns on a plate at different resonant frequencies.','https://physics-simulations.org/simulation/chladni-patterns/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/chladni-patterns/','Physics Simulations',MD5('psim-chladni'),0,1,'iarepo','','approved'),
('Beats and Superposition','Hear and see beat frequency from two interfering sound waves.','https://physics-simulations.org/simulation/beats/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/beats/','Physics Simulations',MD5('psim-beats'),0,1,'iarepo','','approved'),
('Sonic Boom / Mach Cone','Visualize shock waves and Mach cones from supersonic sources.','https://physics-simulations.org/simulation/sonic-boom-mach-cone/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/sonic-boom-mach-cone/','Physics Simulations',MD5('psim-sonic-boom'),0,1,'iarepo','','approved');

-- ── Classical Mechanics ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Newton\'s Cradle','Classic Newton\'s cradle demonstrating conservation of momentum and energy.','https://physics-simulations.org/simulation/newtons-cradle/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/newtons-cradle/','Physics Simulations',MD5('psim-cradle'),0,1,'iarepo','','approved'),
('Double Pendulum (Chaos)','Explore chaotic motion with a double pendulum — sensitive to initial conditions.','https://physics-simulations.org/simulation/double-pendulum/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/double-pendulum/','Physics Simulations',MD5('psim-double-pendulum'),0,1,'iarepo','','approved'),
('Coupled Oscillators','Two masses connected by springs showing normal modes and energy transfer.','https://physics-simulations.org/simulation/coupled-oscillators/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/coupled-oscillators/','Physics Simulations',MD5('psim-coupled-osc'),0,1,'iarepo','','approved'),
('Damped Oscillations','Explore underdamped, critically damped, and overdamped oscillations.','https://physics-simulations.org/simulation/damped-oscillations/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/damped-oscillations/','Physics Simulations',MD5('psim-damped'),0,1,'iarepo','','approved'),
('Atwood Machine','Classic Atwood machine with adjustable masses and real-time calculations.','https://physics-simulations.org/simulation/atwood-machine/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/atwood-machine/','Physics Simulations',MD5('psim-atwood'),0,1,'iarepo','','approved'),
('Coriolis Force','Visualize the Coriolis effect on a rotating reference frame.','https://physics-simulations.org/simulation/coriolis-force/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/coriolis-force/','Physics Simulations',MD5('psim-coriolis'),0,1,'iarepo','','approved'),
('Gyroscope / Precession','Explore gyroscopic precession with adjustable spin and torque.','https://physics-simulations.org/simulation/gyroscope-precession/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/gyroscope-precession/','Physics Simulations',MD5('psim-gyroscope'),0,1,'iarepo','','approved');

-- ── Gravity & Orbits ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('N-Body Gravity Simulation','Place multiple masses and watch gravitational interactions — orbits, collisions, chaos.','https://physics-simulations.org/simulation/n-body-gravity/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/n-body-gravity/','Physics Simulations',MD5('psim-nbody'),0,1,'iarepo','','approved'),
('Lagrange Points','Explore the 5 Lagrange points in a two-body gravitational system.','https://physics-simulations.org/simulation/lagrange-points/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/lagrange-points/','Physics Simulations',MD5('psim-lagrange'),0,1,'iarepo','','approved'),
('Gravitational Slingshot','Simulate a spacecraft using planetary gravity assists to change velocity.','https://physics-simulations.org/simulation/gravitational-slingshot/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/gravitational-slingshot/','Physics Simulations',MD5('psim-slingshot'),0,1,'iarepo','','approved'),
('Gravitational Lensing','See how massive objects bend light — simulating Einstein\'s gravitational lensing.','https://physics-simulations.org/simulation/gravitational-lensing/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/gravitational-lensing/','Physics Simulations',MD5('psim-lensing'),0,1,'iarepo','','approved'),
('Tidal Forces','Visualize how differential gravity causes tidal bulges on a body.','https://physics-simulations.org/simulation/tidal-forces/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/tidal-forces/','Physics Simulations',MD5('psim-tidal'),0,1,'iarepo','','approved');

-- ── Electromagnetism ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Faraday\'s Law of Induction','Move a magnet through a coil and observe induced EMF and current.','https://physics-simulations.org/simulation/faradays-law/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/faradays-law/','Physics Simulations',MD5('psim-faraday'),0,1,'iarepo','','approved'),
('Lorentz Force on Charged Particle','See how electric and magnetic fields deflect a moving charge.','https://physics-simulations.org/simulation/lorentz-force/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/lorentz-force/','Physics Simulations',MD5('psim-lorentz'),0,1,'iarepo','','approved'),
('Biot-Savart Law','Visualize the magnetic field generated by current-carrying wires.','https://physics-simulations.org/simulation/biot-savart-law/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/biot-savart-law/','Physics Simulations',MD5('psim-biotsavart'),0,1,'iarepo','','approved'),
('RC Circuit','Charge and discharge a capacitor through a resistor — see voltage/current curves.','https://physics-simulations.org/simulation/rc-circuit/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/rc-circuit/','Physics Simulations',MD5('psim-rc-circuit'),0,1,'iarepo','','approved'),
('RLC Circuit / Resonance','Explore resonance in an RLC circuit with adjustable components.','https://physics-simulations.org/simulation/rlc-circuit-resonance/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/rlc-circuit-resonance/','Physics Simulations',MD5('psim-rlc'),0,1,'iarepo','','approved');

-- ── Optics ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Total Internal Reflection','Explore the critical angle and total internal reflection in optical fibers.','https://physics-simulations.org/simulation/total-internal-reflection/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/total-internal-reflection/','Physics Simulations',MD5('psim-tir'),0,1,'iarepo','','approved'),
('Prism Light Dispersion','Split white light into its spectrum through a prism.','https://physics-simulations.org/simulation/prism-light-dispersion/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/prism-light-dispersion/','Physics Simulations',MD5('psim-prism'),0,1,'iarepo','','approved'),
('Concave & Convex Mirrors','Ray diagrams for concave and convex mirrors with movable objects.','https://physics-simulations.org/simulation/mirror-reflection-concave-convex/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/simulation/mirror-reflection-concave-convex/','Physics Simulations',MD5('psim-mirrors'),0,1,'iarepo','','approved'),
('Rayleigh Scattering','Why is the sky blue? See how wavelength-dependent scattering works.','https://physics-simulations.org/simulation/rayleigh-scattering/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/rayleigh-scattering/','Physics Simulations',MD5('psim-rayleigh'),0,1,'iarepo','','approved');

-- ── Thermodynamics ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Brownian Motion Simulation','Watch random molecular collisions cause visible particle jitter.','https://physics-simulations.org/simulation/brownian-motion/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/brownian-motion/','Physics Simulations',MD5('psim-brownian'),0,1,'iarepo','','approved'),
('Carnot Engine','Step through the Carnot cycle on a PV diagram — isotherms and adiabats.','https://physics-simulations.org/simulation/carnot-engine/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/carnot-engine/','Physics Simulations',MD5('psim-carnot'),0,1,'iarepo','','approved'),
('Bernoulli\'s Principle','Visualize pressure and velocity changes in fluid flow through varying cross-sections.','https://physics-simulations.org/simulation/bernoullis-principle/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/bernoullis-principle/','Physics Simulations',MD5('psim-bernoulli'),0,1,'iarepo','','approved'),
('Blackbody Radiation','Explore Planck\'s law — see how the emission spectrum shifts with temperature.','https://physics-simulations.org/simulation/blackbody-radiation/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/blackbody-radiation/','Physics Simulations',MD5('psim-blackbody'),0,1,'iarepo','','approved'),
('Kinetic Theory of Gases','Visualize gas molecules in a box — temperature, pressure, and the Maxwell distribution.','https://physics-simulations.org/simulation/kinetic-theory-of-gases/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/kinetic-theory-of-gases/','Physics Simulations',MD5('psim-kinetic-theory'),0,1,'iarepo','','approved');

-- ── Quantum Mechanics ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Quantum Tunneling','Watch a particle tunnel through a potential barrier — adjustable energy and width.','https://physics-simulations.org/simulation/quantum-tunneling/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/quantum-tunneling/','Physics Simulations',MD5('psim-tunneling'),0,1,'iarepo','','approved'),
('Photoelectric Effect','Shine light on a metal surface and observe electron emission — Einstein\'s theory.','https://physics-simulations.org/simulation/photoelectric-effect/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/photoelectric-effect/','Physics Simulations',MD5('psim-photoelectric'),0,1,'iarepo','','approved'),
('Stern-Gerlach Experiment','Simulate spin measurement of silver atoms in an inhomogeneous magnetic field.','https://physics-simulations.org/simulation/stern-gerlach/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/stern-gerlach/','Physics Simulations',MD5('psim-stern-gerlach'),0,1,'iarepo','','approved'),
('Particle in a Box','Visualize quantum energy levels and wavefunctions in an infinite potential well.','https://physics-simulations.org/simulation/particle-in-a-box/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/particle-in-a-box/','Physics Simulations',MD5('psim-particle-box'),0,1,'iarepo','','approved'),
('Schrödinger Equation (1D)','Solve and visualize the time-dependent Schrödinger equation.','https://physics-simulations.org/simulation/schrodinger-equation-1d/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/schrodinger-equation-1d/','Physics Simulations',MD5('psim-schrodinger'),0,1,'iarepo','','approved'),
('Hydrogen Orbitals','Visualize electron probability distributions for hydrogen atom orbitals.','https://physics-simulations.org/simulation/hydrogen-orbitals/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/hydrogen-orbitals/','Physics Simulations',MD5('psim-hydrogen-orbitals'),0,1,'iarepo','','approved'),
('Compton Scattering','Simulate X-ray photon scattering off electrons — wavelength shift.','https://physics-simulations.org/simulation/compton-scattering/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/compton-scattering/','Physics Simulations',MD5('psim-compton'),0,1,'iarepo','','approved'),
('Uncertainty Principle','Interactive visualization of Heisenberg\'s uncertainty principle — Δx·Δp ≥ ℏ/2.','https://physics-simulations.org/simulation/uncertainty-principle/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/uncertainty-principle/','Physics Simulations',MD5('psim-uncertainty'),0,1,'iarepo','','approved');

-- ── Relativity ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Time Dilation','Visualize how time slows at relativistic speeds — light clocks and muon decay.','https://physics-simulations.org/simulation/time-dilation/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/time-dilation/','Physics Simulations',MD5('psim-time-dilation'),0,1,'iarepo','','approved'),
('Twin Paradox','Interactive twin paradox — compare aging of twins at different velocities.','https://physics-simulations.org/simulation/twin-paradox/','url','Physics','community','en','ib',1,'https://physics-simulations.org/simulation/twin-paradox/','Physics Simulations',MD5('psim-twin-paradox'),0,1,'iarepo','','approved'),
('Spacetime Diagrams','Draw and explore Minkowski spacetime diagrams with worldlines and light cones.','https://physics-simulations.org/simulation/spacetime-diagrams/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/spacetime-diagrams/','Physics Simulations',MD5('psim-spacetime'),0,1,'iarepo','','approved');

-- ── Chaos & Complex Systems ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Lorenz Attractor','Visualize the classic chaotic Lorenz attractor in 3D.','https://physics-simulations.org/simulation/lorenz-attractor/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/lorenz-attractor/','Physics Simulations',MD5('psim-lorenz'),0,1,'iarepo','','approved'),
('Mandelbrot Fractal Explorer','Zoom into the Mandelbrot set and explore infinite fractal complexity.','https://physics-simulations.org/simulation/mandelbrot-fractal-explorer/','url','Mathematics','community','en','university',2,'https://physics-simulations.org/simulation/mandelbrot-fractal-explorer/','Physics Simulations',MD5('psim-mandelbrot'),0,1,'iarepo','','approved'),
('Cellular Automata','Explore Conway\'s Game of Life and other cellular automata rules.','https://physics-simulations.org/simulation/cellular-automata/','url','Computer Science','community','en','ib',7,'https://physics-simulations.org/simulation/cellular-automata/','Physics Simulations',MD5('psim-cellular'),0,1,'iarepo','','approved'),
('Reaction-Diffusion Patterns','Generate Turing patterns — spots, stripes, and spirals from reaction-diffusion systems.','https://physics-simulations.org/simulation/reaction-diffusion-patterns/','url','Physics','community','en','university',1,'https://physics-simulations.org/simulation/reaction-diffusion-patterns/','Physics Simulations',MD5('psim-reaction-diff'),0,1,'iarepo','','approved'),
('Lissajous Figures','Create beautiful patterns from two perpendicular harmonic oscillations.','https://physics-simulations.org/simulation/lissajous-figures/','url','Mathematics','community','en','secondary',2,'https://physics-simulations.org/simulation/lissajous-figures/','Physics Simulations',MD5('psim-lissajous'),0,1,'iarepo','','approved');

-- ── Tags ──
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'simulation' FROM resources WHERE source_name = 'Physics Simulations' AND id > 128;
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'interactive' FROM resources WHERE source_name = 'Physics Simulations' AND id > 128;
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'html5' FROM resources WHERE source_name = 'Physics Simulations' AND id > 128;
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'physics-simulations.org' FROM resources WHERE source_name = 'Physics Simulations' AND id > 128;
