-- ================================================================
-- seed_catalog_v2.sql — Mega catalog: oPhysics, Walter Fendt,
-- Physics Classroom, Concord Consortium, Falstad, BioInteractive
-- ================================================================
-- author_tenant_name va explícito en cada fila: la columna es NOT NULL
-- SIN DEFAULT y con STRICT_TRANS_TABLES (producción: MariaDB 11.8) el
-- INSERT entero aborta con ERROR 1364 si se omite. Valor '' = el mismo
-- que escribe la app para recursos de comunidad (api/resources.php).

-- ── oPhysics (Tom Walsh) — Free for education ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Projectile Motion Simulator','Simulate projectile motion with adjustable angle, speed, and gravity. Visualize trajectory in real-time.','https://ophysics.com/k8.html','url','Physics','community','en','secondary',1,'https://ophysics.com/k8.html','oPhysics',MD5('https://ophysics.com/k8.html'),0,1,'iarepo','','approved'),
('Vector Addition','Add vectors graphically and see components. Interactive drag-and-drop interface.','https://ophysics.com/k1.html','url','Physics','community','en','secondary',1,'https://ophysics.com/k1.html','oPhysics',MD5('https://ophysics.com/k1.html'),0,1,'iarepo','','approved'),
('Simple Pendulum','Explore simple pendulum motion with adjustable length and gravity.','https://ophysics.com/w1.html','url','Physics','community','en','secondary',1,'https://ophysics.com/w1.html','oPhysics',MD5('https://ophysics.com/w1.html'),0,1,'iarepo','','approved'),
('Standing Waves on a String','Visualize standing wave patterns with adjustable frequency and tension.','https://ophysics.com/w5.html','url','Physics','community','en','ib',1,'https://ophysics.com/w5.html','oPhysics',MD5('https://ophysics.com/w5.html'),0,1,'iarepo','','approved'),
('Elastic vs Inelastic Collisions','Compare elastic and inelastic collisions with momentum and energy analysis.','https://ophysics.com/m1.html','url','Physics','community','en','secondary',1,'https://ophysics.com/m1.html','oPhysics',MD5('https://ophysics.com/m1.html'),0,1,'iarepo','','approved'),
('Doppler Effect','Visualize the Doppler effect for sound waves with a moving source.','https://ophysics.com/w9.html','url','Physics','community','en','ib',1,'https://ophysics.com/w9.html','oPhysics',MD5('https://ophysics.com/w9.html'),0,1,'iarepo','','approved'),
('Snells Law Refraction','Explore refraction of light at an interface using Snells Law.','https://ophysics.com/l2.html','url','Physics','community','en','secondary',1,'https://ophysics.com/l2.html','oPhysics',MD5('https://ophysics.com/l2.html'),0,1,'iarepo','','approved'),
('Thin Lens Optics','Ray diagrams for converging and diverging thin lenses.','https://ophysics.com/l11.html','url','Physics','community','en','ib',1,'https://ophysics.com/l11.html','oPhysics',MD5('https://ophysics.com/l11.html'),0,1,'iarepo','','approved'),
('Uniform Circular Motion','Visualize velocity, acceleration, and force in circular motion.','https://ophysics.com/f1.html','url','Physics','community','en','secondary',1,'https://ophysics.com/f1.html','oPhysics',MD5('https://ophysics.com/f1.html'),0,1,'iarepo','','approved'),
('Diffraction and Interference','Single and double slit diffraction patterns with adjustable parameters.','https://ophysics.com/l8.html','url','Physics','community','en','ib',1,'https://ophysics.com/l8.html','oPhysics',MD5('https://ophysics.com/l8.html'),0,1,'iarepo','','approved');

-- ── Walter Fendt — HTML5 Physics/Math Applets ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Newtons Second Law','Experiment with force, mass, and acceleration on a frictionless surface.','https://www.walter-fendt.de/html5/phen/newtonlaw2_en.htm','url','Physics','community','en','secondary',1,'https://www.walter-fendt.de/html5/phen/newtonlaw2_en.htm','Walter Fendt',MD5('https://www.walter-fendt.de/html5/phen/newtonlaw2_en.htm'),0,1,'iarepo','','approved'),
('Kepler\'s Laws of Planetary Motion','Visualize elliptical orbits and area law for planetary motion.','https://www.walter-fendt.de/html5/phen/keplerlaw1_en.htm','url','Physics','community','en','ib',1,'https://www.walter-fendt.de/html5/phen/keplerlaw1_en.htm','Walter Fendt',MD5('https://www.walter-fendt.de/html5/phen/keplerlaw1_en.htm'),0,1,'iarepo','','approved'),
('Electromagnetic Wave','Animated electromagnetic wave showing E and B field oscillations.','https://www.walter-fendt.de/html5/phen/emwave_en.htm','url','Physics','community','en','ib',1,'https://www.walter-fendt.de/html5/phen/emwave_en.htm','Walter Fendt',MD5('https://www.walter-fendt.de/html5/phen/emwave_en.htm'),0,1,'iarepo','','approved'),
('Inclined Plane Forces','Decompose forces on an inclined plane with adjustable angle and friction.','https://www.walter-fendt.de/html5/phen/inclinedplane_en.htm','url','Physics','community','en','secondary',1,'https://www.walter-fendt.de/html5/phen/inclinedplane_en.htm','Walter Fendt',MD5('https://www.walter-fendt.de/html5/phen/inclinedplane_en.htm'),0,1,'iarepo','','approved'),
('Resultant of Forces','Add two force vectors and find the resultant graphically.','https://www.walter-fendt.de/html5/phen/resultant_en.htm','url','Physics','community','en','secondary',1,'https://www.walter-fendt.de/html5/phen/resultant_en.htm','Walter Fendt',MD5('https://www.walter-fendt.de/html5/phen/resultant_en.htm'),0,1,'iarepo','','approved');

-- ── The Physics Classroom — Free Interactives ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Name That Motion','Interpret position-time and velocity-time graphs by matching them to animations.','https://www.physicsclassroom.com/Physics-Interactives/1-D-Kinematics/Name-That-Motion/Name-That-Motion-Interactive','url','Physics','community','en','secondary',1,'https://www.physicsclassroom.com/Physics-Interactives/1-D-Kinematics/Name-That-Motion/Name-That-Motion-Interactive','The Physics Classroom',MD5('tpc-name-that-motion'),0,1,'iarepo','','approved'),
('Projectile Simulator','Launch projectiles at various angles and speeds. Analyze range, height, and time.','https://www.physicsclassroom.com/Physics-Interactives/Vectors-and-Projectiles/Projectile-Simulator/Projectile-Simulator-Interactive','url','Physics','community','en','secondary',1,'https://www.physicsclassroom.com/Physics-Interactives/Vectors-and-Projectiles/Projectile-Simulator/Projectile-Simulator-Interactive','The Physics Classroom',MD5('tpc-projectile-sim'),0,1,'iarepo','','approved'),
('Roller Coaster Model','Design a roller coaster and analyze energy transformations along the track.','https://www.physicsclassroom.com/Physics-Interactives/Work-and-Energy/Roller-Coaster-Model/Roller-Coaster-Model-Interactive','url','Physics','community','en','secondary',1,'https://www.physicsclassroom.com/Physics-Interactives/Work-and-Energy/Roller-Coaster-Model/Roller-Coaster-Model-Interactive','The Physics Classroom',MD5('tpc-roller-coaster'),0,1,'iarepo','','approved'),
('Orbital Motion','Explore satellite orbits and gravitational fields around planets.','https://www.physicsclassroom.com/Physics-Interactives/Circular-and-Satellite-Motion/Orbital-Motion/Orbital-Motion-Interactive','url','Physics','community','en','ib',1,'https://www.physicsclassroom.com/Physics-Interactives/Circular-and-Satellite-Motion/Orbital-Motion/Orbital-Motion-Interactive','The Physics Classroom',MD5('tpc-orbital-motion'),0,1,'iarepo','','approved'),
('Collision Carts','Simulate elastic and inelastic collisions between carts on a track.','https://www.physicsclassroom.com/Physics-Interactives/Momentum-and-Collisions/Collision-Carts/Collision-Carts-Interactive','url','Physics','community','en','secondary',1,'https://www.physicsclassroom.com/Physics-Interactives/Momentum-and-Collisions/Collision-Carts/Collision-Carts-Interactive','The Physics Classroom',MD5('tpc-collision-carts'),0,1,'iarepo','','approved');

-- ── Concord Consortium (Lab) — Open Source HTML5 ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Gas Laws: Pressure-Volume','Explore Boyle\'s Law with an interactive piston and gas molecules.','https://lab.concord.org/embeddable.html#interactives/sam/gas-laws/3-volume-pressure-relationship.json','url','Chemistry','community','en','secondary',2,'https://lab.concord.org/','Concord Consortium',MD5('concord-gas-pv'),0,1,'iarepo','','approved'),
('Phase Change: Molecular View','Watch molecules transition between solid, liquid, and gas phases.','https://lab.concord.org/embeddable.html#interactives/sam/phase-change/3-phase-changes-caused-by-energy-input.json','url','Chemistry','community','en','secondary',2,'https://lab.concord.org/','Concord Consortium',MD5('concord-phase-change'),0,1,'iarepo','','approved'),
('Intermolecular Attractions','Explore how molecular polarity affects intermolecular forces.','https://lab.concord.org/embeddable.html#interactives/sam/intermolecular-attractions/5-strengthening-london-dispersion-attractions.json','url','Chemistry','community','en','ib',2,'https://lab.concord.org/','Concord Consortium',MD5('concord-intermolecular'),0,1,'iarepo','','approved'),
('Diffusion and Osmosis','Simulate diffusion of molecules across a semipermeable membrane.','https://lab.concord.org/embeddable.html#interactives/sam/diffusion/2-two-atoms-and-membrane.json','url','Biology','community','en','secondary',4,'https://lab.concord.org/','Concord Consortium',MD5('concord-diffusion'),0,1,'iarepo','','approved');

-- ── Falstad — HTML5 Circuit/Math Sims ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Circuit Simulator','Build and analyze DC/AC circuits with resistors, capacitors, inductors, and more.','https://www.falstad.com/circuit/circuitjs.html','url','Physics','community','en','secondary',1,'https://www.falstad.com/circuit/circuitjs.html','Falstad',MD5('https://www.falstad.com/circuit/circuitjs.html'),0,1,'iarepo','','approved'),
('Ripple Tank Simulator','Visualize wave phenomena: interference, diffraction, and reflection in 2D.','https://www.falstad.com/ripple/','url','Physics','community','en','ib',1,'https://www.falstad.com/ripple/','Falstad',MD5('https://www.falstad.com/ripple/'),0,1,'iarepo','','approved'),
('2D Electromagnetic Simulation','Visualize electric and magnetic fields in 2D with interactive charges.','https://www.falstad.com/emstatic/','url','Physics','community','en','university',1,'https://www.falstad.com/emstatic/','Falstad',MD5('https://www.falstad.com/emstatic/'),0,1,'iarepo','','approved');

-- ── BioInteractive (HHMI) — Biology ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Lizard Evolution Virtual Lab','Explore natural selection and adaptation in Anolis lizards across Caribbean islands.','https://media.hhmi.org/biointeractive/vlabs/lizard-evolution/','url','Biology','community','en','ib',4,'https://www.biointeractive.org/classroom-resources/lizard-evolution-virtual-lab','BioInteractive (HHMI)',MD5('hhmi-lizard-evolution'),0,1,'iarepo','','approved'),
('Bacterial Identification Lab','Use lab techniques to identify unknown bacterial samples.','https://media.hhmi.org/biointeractive/vlabs/bacterial-id/','url','Biology','community','en','ib',4,'https://www.biointeractive.org/classroom-resources/bacterial-identification-virtual-lab','BioInteractive (HHMI)',MD5('hhmi-bacterial-id'),0,1,'iarepo','','approved'),
('Human Body Map','Interactive anatomy explorer with organ systems overlay.','https://media.hhmi.org/biointeractive/click/humanbodymap/','url','Biology','community','en','secondary',4,'https://www.biointeractive.org/','BioInteractive (HHMI)',MD5('hhmi-body-map'),0,1,'iarepo','','approved');

-- ── GeoGebra extras — Math ──
INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, author_tenant_name, moderation_status) VALUES
('Probability Simulator','Run experiments with coins, dice, and spinners. Visualize distributions.','https://www.geogebra.org/probability','url','Mathematics','community','en','secondary',3,'https://www.geogebra.org/probability','GeoGebra',MD5('geogebra-probability'),0,1,'iarepo','','approved'),
('GeoGebra CAS Calculator','Computer Algebra System — solve equations, factor, expand symbolically.','https://www.geogebra.org/cas','url','Mathematics','community','en','university',3,'https://www.geogebra.org/cas','GeoGebra',MD5('geogebra-cas'),0,1,'iarepo','','approved'),
('GeoGebra 3D Calculator','Explore 3D surfaces, vectors, and coordinate geometry interactively.','https://www.geogebra.org/3d','url','Mathematics','community','en','university',3,'https://www.geogebra.org/3d','GeoGebra',MD5('geogebra-3d-calc'),0,1,'iarepo','','approved'),
('GeoGebra Scientific Calculator','Full scientific calculator with fraction, trig, and stats functions.','https://www.geogebra.org/scientific','url','Mathematics','community','en','secondary',3,'https://www.geogebra.org/scientific','GeoGebra',MD5('geogebra-scientific'),0,1,'iarepo','','approved');

-- ── Tags for new resources ──
INSERT IGNORE INTO resource_tags (resource_id, tag)
SELECT id, 'simulation' FROM resources WHERE source_name IN ('oPhysics','Walter Fendt','The Physics Classroom','Falstad') AND id > 38;
INSERT IGNORE INTO resource_tags (resource_id, tag)
SELECT id, 'interactive' FROM resources WHERE id > 38;
INSERT IGNORE INTO resource_tags (resource_id, tag)
SELECT id, 'free' FROM resources WHERE id > 38;
INSERT IGNORE INTO resource_tags (resource_id, tag)
SELECT id, LOWER(source_name) FROM resources WHERE source_name IS NOT NULL AND id > 38;
