-- ================================================================
-- seed_catalog_v5b.sql — Remaining 77 sims from physics-simulations.org
-- These were NOT in v5 (the first 50)
-- ================================================================

INSERT INTO resources (title, description, code_content, code_type, subject_area, visibility, lang, level, category_id, source_url, source_name, content_hash, author_tenant_id, author_user_id, author_display_name, moderation_status) VALUES
-- Wave Phenomena (missing 6)
('Single-Slit Diffraction','Diffraction envelope and fringe spreading through one slit.','https://physics-simulations.org/simulation/single-slit-diffraction/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-single-slit'),0,1,'iarepo','approved'),
('Resonance','Driven oscillator resonance peak and response amplitude.','https://physics-simulations.org/simulation/resonance/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-resonance'),0,1,'iarepo','approved'),
('Wave Reflection','Fixed, free, and partial boundary reflections and transmission.','https://physics-simulations.org/simulation/wave-reflection/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-wave-reflect'),0,1,'iarepo','approved'),
('Constructive & Destructive Interference','Phase-dependent addition of two same-frequency waves.','https://physics-simulations.org/simulation/constructive-destructive-interference/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-interference'),0,1,'iarepo','approved'),
('Wave Polarization','Linear, circular, and elliptical polarization states.','https://physics-simulations.org/simulation/wave-polarization/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-polarization'),0,1,'iarepo','approved'),
('Huygens Principle','Secondary wavelets form advancing wavefronts through apertures.','https://physics-simulations.org/simulation/huygens-principle/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-huygens'),0,1,'iarepo','approved'),

-- Classical Mechanics (missing 14)
('Newton''s Laws of Motion','Force, mass, friction, and acceleration in cart dynamics.','https://physics-simulations.org/simulation/newtons-laws-of-motion/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-newton-laws'),0,1,'iarepo','approved'),
('Projectile Motion (PS)','Launch projectiles with adjustable angle and velocity.','https://physics-simulations.org/simulation/projectile-motion/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-projectile'),0,1,'iarepo','approved'),
('Inclined Plane (PS)','Force decomposition and friction on a ramp.','https://physics-simulations.org/simulation/inclined-plane/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-inclined'),0,1,'iarepo','approved'),
('Friction: Static vs Kinetic','Threshold behavior and motion under static and kinetic friction.','https://physics-simulations.org/simulation/friction-static-vs-kinetic/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-friction'),0,1,'iarepo','approved'),
('Circular Motion','Velocity and centripetal acceleration in uniform circular motion.','https://physics-simulations.org/simulation/circular-motion/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-circular'),0,1,'iarepo','approved'),
('Centripetal Force','Radial acceleration and vector relationships in circular motion.','https://physics-simulations.org/simulation/centripetal-force/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-centripetal'),0,1,'iarepo','approved'),
('Center of Mass','Weighted average position of a multi-mass system.','https://physics-simulations.org/simulation/center-of-mass/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-center-mass'),0,1,'iarepo','approved'),
('Simple Pendulum (PS)','Oscillation under gravity with real-time graph.','https://physics-simulations.org/simulation/simple-pendulum/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-simple-pend'),0,1,'iarepo','approved'),
('Forced Oscillations','Driven response, resonance, and phase lag.','https://physics-simulations.org/simulation/forced-oscillations/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-forced-osc'),0,1,'iarepo','approved'),
('Spring-Mass Oscillator','Hooke''s law with damping.','https://physics-simulations.org/simulation/spring-mass-oscillator/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-spring-mass'),0,1,'iarepo','approved'),
('Conservation of Momentum','Collision outcomes under momentum conservation and restitution.','https://physics-simulations.org/simulation/conservation-of-momentum/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-cons-momentum'),0,1,'iarepo','approved'),
('Inelastic Collision (1D)','Momentum conserved while kinetic energy decreases.','https://physics-simulations.org/simulation/inelastic-collision-1d/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-inelastic'),0,1,'iarepo','approved'),
('Elastic Collisions (2D)','Momentum and energy conservation in 2D collisions.','https://physics-simulations.org/simulation/elastic-collisions/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-elastic-2d'),0,1,'iarepo','approved'),
('Lever & Pulley','Mechanical advantage from lever arms and pulley geometry.','https://physics-simulations.org/simulation/lever-pulley/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-lever-pulley'),0,1,'iarepo','approved'),

-- Gravity (missing 3)
('Kepler''s Orbits','Elliptical orbits with changing speed and equal-area sweeps.','https://physics-simulations.org/simulation/keplers-orbits/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-kepler-orbits'),0,1,'iarepo','approved'),
('Gravitational Field','Field vectors and potential landscape around gravitating masses.','https://physics-simulations.org/simulation/gravitational-field/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-grav-field'),0,1,'iarepo','approved'),
('Escape Velocity','Launch speed threshold for bound and unbound trajectories.','https://physics-simulations.org/simulation/escape-velocity/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-escape-vel'),0,1,'iarepo','approved'),
('Hohmann Transfer Orbit','Two-burn transfer ellipse between circular orbits.','https://physics-simulations.org/simulation/hohmann-transfer/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-hohmann'),0,1,'iarepo','approved'),

-- Electromagnetism (missing 9)
('Electric Field Lines','Visualize fields from point charges.','https://physics-simulations.org/simulation/electric-field-lines/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-efield-lines'),0,1,'iarepo','approved'),
('Magnetic Field Lines','Dipole field lines and field-strength regions around a magnet.','https://physics-simulations.org/simulation/magnetic-field-lines/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-bfield-lines'),0,1,'iarepo','approved'),
('Coulomb''s Law','Inverse-square electric force between point charges.','https://physics-simulations.org/simulation/coulombs-law/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-coulomb'),0,1,'iarepo','approved'),
('EM Wave Propagation','Coupled oscillating E and B fields traveling through space.','https://physics-simulations.org/simulation/electromagnetic-wave-propagation/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-emwave'),0,1,'iarepo','approved'),
('Lenz''s Law','Induced currents oppose changes in magnetic flux.','https://physics-simulations.org/simulation/lenzs-law/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-lenz'),0,1,'iarepo','approved'),
('Cyclotron Motion','Circular motion of a charged particle in a uniform magnetic field.','https://physics-simulations.org/simulation/cyclotron-motion/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-cyclotron'),0,1,'iarepo','approved'),
('Ohm''s Law Circuit','Voltage, resistance, current, and power in a simple circuit.','https://physics-simulations.org/simulation/ohms-law-circuit/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-ohm'),0,1,'iarepo','approved'),
('Kirchhoff''s Laws','Current splitting and loop voltage balance in a branch circuit.','https://physics-simulations.org/simulation/kirchhoffs-laws/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-kirchhoff'),0,1,'iarepo','approved'),
('AC vs DC','Time-varying AC compared with steady DC across a load.','https://physics-simulations.org/simulation/ac-vs-dc/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-acdc'),0,1,'iarepo','approved'),

-- Optics (missing 7)
('Snell''s Law (Refraction)','Light bending at material boundaries.','https://physics-simulations.org/simulation/snells-law-refraction/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-snell'),0,1,'iarepo','approved'),
('Thin Lens Simulation','Ray tracing and image formation with thin lenses.','https://physics-simulations.org/simulation/thin-lens-simulation/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-thin-lens'),0,1,'iarepo','approved'),
('Brewster''s Angle','P-polarized reflection vanishes at a special incidence angle.','https://physics-simulations.org/simulation/brewsters-angle/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-brewster'),0,1,'iarepo','approved'),
('Fresnel Diffraction','Near-field diffraction pattern from phase summation.','https://physics-simulations.org/simulation/fresnel-diffraction/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-fresnel'),0,1,'iarepo','approved'),
('Chromatic Aberration','Different wavelengths focus at different image distances.','https://physics-simulations.org/simulation/chromatic-aberration/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-chromatic'),0,1,'iarepo','approved'),
('Thin Film Interference','Reflected color varies with film thickness and angle.','https://physics-simulations.org/simulation/thin-film-interference/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-thin-film'),0,1,'iarepo','approved'),
('Optical Fiber Light Guide','Guiding by total internal reflection in a core-cladding fiber.','https://physics-simulations.org/simulation/optical-fiber-light-guide/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-optical-fiber'),0,1,'iarepo','approved'),

-- Thermodynamics (missing 8)
('Ideal Gas Law','Particle box and piston illustrating PV = nRT.','https://physics-simulations.org/simulation/ideal-gas-law/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-ideal-gas'),0,1,'iarepo','approved'),
('Heat Conduction','Temperature diffusion through a rod.','https://physics-simulations.org/simulation/heat-conduction/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-heat-cond'),0,1,'iarepo','approved'),
('Entropy Visualization','Mixing and multiplicity as a visual entropy proxy.','https://physics-simulations.org/simulation/entropy-visualization/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-entropy'),0,1,'iarepo','approved'),
('Phase Transitions','Heating curve with melting and boiling plateaus.','https://physics-simulations.org/simulation/phase-transitions/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-phase-trans'),0,1,'iarepo','approved'),
('Laminar vs Turbulent Flow','Ordered flow transitioning toward turbulent mixing.','https://physics-simulations.org/simulation/laminar-vs-turbulent-flow/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-laminar-turb'),0,1,'iarepo','approved'),
('Venturi Effect','Throat acceleration and pressure drop in a constriction.','https://physics-simulations.org/simulation/venturi-effect/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-venturi'),0,1,'iarepo','approved'),
('Convection Cells','Buoyancy-driven circulation from heated boundaries.','https://physics-simulations.org/simulation/convection-cells/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-convection'),0,1,'iarepo','approved'),
('Thermal Expansion','Linear expansion of solids with temperature.','https://physics-simulations.org/simulation/thermal-expansion/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-thermal-exp'),0,1,'iarepo','approved'),
('Archimedes'' Principle','Buoyancy from displaced fluid weight.','https://physics-simulations.org/simulation/archimedes-principle/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-archimedes'),0,1,'iarepo','approved'),
('Maxwell-Boltzmann Distribution','Gas particle speed distribution.','https://physics-simulations.org/simulation/maxwell-boltzmann/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-maxwell-bolt'),0,1,'iarepo','approved'),

-- Quantum (missing 15)
('Quantum Superposition','Interference from combining quantum amplitudes.','https://physics-simulations.org/simulation/quantum-superposition/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-superposition'),0,1,'iarepo','approved'),
('Electron Diffraction','Matter-wave interference pattern from electron paths.','https://physics-simulations.org/simulation/electron-diffraction/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-electron-diff'),0,1,'iarepo','approved'),
('Bloch Sphere','Qubit state visualization on a Bloch sphere projection.','https://physics-simulations.org/simulation/bloch-sphere/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-bloch'),0,1,'iarepo','approved'),
('Band Gap Visualization','Valence-conduction bands and energy gap visualization.','https://physics-simulations.org/simulation/band-gap/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-bandgap'),0,1,'iarepo','approved'),
('Wave Packet','Localized quantum packet propagation and spreading.','https://physics-simulations.org/simulation/wave-packet/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-wavepacket'),0,1,'iarepo','approved'),
('Quantum Harmonic Oscillator','Discrete oscillator levels and wavefunctions.','https://physics-simulations.org/simulation/quantum-harmonic-oscillator/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-qho'),0,1,'iarepo','approved'),
('Aharonov-Bohm Effect','Phase-shifted interference from confined magnetic flux.','https://physics-simulations.org/simulation/aharonov-bohm-effect/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-aharonov'),0,1,'iarepo','approved'),
('de Broglie Wavelength','Matter wavelength versus momentum with fringe preview.','https://physics-simulations.org/simulation/de-broglie-wavelength/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-debroglie'),0,1,'iarepo','approved'),
('Photon Polarization','Polarization state and analyzer transmission.','https://physics-simulations.org/simulation/photon-polarization/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-photon-pol'),0,1,'iarepo','approved'),
('Hydrogen-like Atom','Toy radial probability and shell scaling with n and Z.','https://physics-simulations.org/simulation/hydrogen-like-atom/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-hydrogen-atom'),0,1,'iarepo','approved'),
('Quantum Jump','Two-level state switching and jump timeline.','https://physics-simulations.org/simulation/quantum-jump/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-qjump'),0,1,'iarepo','approved'),
('Transmission Coefficient','Barrier transmission versus energy and width.','https://physics-simulations.org/simulation/transmission-coefficient/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-transmission'),0,1,'iarepo','approved'),
('Probability Current','Flow of probability from phase gradients.','https://physics-simulations.org/simulation/probability-current/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-prob-current'),0,1,'iarepo','approved'),
('Avoided Crossing','Coupling opens a gap where levels would cross.','https://physics-simulations.org/simulation/avoided-crossing/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-avoided'),0,1,'iarepo','approved'),
('Landau-Zener Transition','Non-adiabatic transitions through avoided crossings.','https://physics-simulations.org/simulation/landau-zener-transition/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-landau-zener'),0,1,'iarepo','approved'),
('Open Quantum System (Decoherence)','Environmental coupling damps quantum coherence.','https://physics-simulations.org/simulation/open-quantum-system-decoherence/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-decoherence'),0,1,'iarepo','approved'),
('Quantum Tomography','Reconstruct qubit state from basis measurements.','https://physics-simulations.org/simulation/quantum-tomography/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-tomography'),0,1,'iarepo','approved'),
('Quantum Contextuality','Toy context-dependent measurement witness.','https://physics-simulations.org/simulation/quantum-contextuality/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-contextuality'),0,1,'iarepo','approved'),
('Landau Levels','Magnetic-field quantized cyclotron energy levels.','https://physics-simulations.org/simulation/landau-levels/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-landau-levels'),0,1,'iarepo','approved'),
('Fano Resonance','Asymmetric resonance from path interference.','https://physics-simulations.org/simulation/fano-resonance/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-fano'),0,1,'iarepo','approved'),
('Quantum Heat Engine','Toy heat-engine cycle with quantum working system.','https://physics-simulations.org/simulation/quantum-heat-engine/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-qheat-engine'),0,1,'iarepo','approved'),

-- Relativity (missing 3)
('Length Contraction','Moving lengths contract along the motion direction.','https://physics-simulations.org/simulation/length-contraction/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-length-contr'),0,1,'iarepo','approved'),
('Lorentz Transformation','Transform events between inertial frames.','https://physics-simulations.org/simulation/lorentz-transformation/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-lorentz-transf'),0,1,'iarepo','approved'),
('Light Cone Visualization','Causal structure and spacelike/timelike separation.','https://physics-simulations.org/simulation/light-cone-visualization/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-lightcone'),0,1,'iarepo','approved'),

-- Chaos (missing 4)
('Logistic Map / Bifurcation','Period-doubling route to chaos in a nonlinear map.','https://physics-simulations.org/simulation/logistic-map-bifurcation-diagram/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-logistic'),0,1,'iarepo','approved'),
('Percolation Simulation','Spanning clusters and threshold behavior.','https://physics-simulations.org/simulation/percolation-simulation/','url','Physics','community','en','university',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-percolation'),0,1,'iarepo','approved'),
('Flocking / Boids Algorithm','Emergent flocking from local motion rules.','https://physics-simulations.org/simulation/flocking-boids-algorithm/','url','Physics','community','en','ib',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-boids'),0,1,'iarepo','approved'),
('Moiré Patterns','Large fringes from overlapping line grids.','https://physics-simulations.org/simulation/moire-patterns/','url','Physics','community','en','secondary',1,'https://physics-simulations.org/','Physics Simulations',MD5('psim-moire'),0,1,'iarepo','approved');

-- Tags
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'simulation' FROM resources WHERE source_name = 'Physics Simulations' AND id > 178;
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'interactive' FROM resources WHERE source_name = 'Physics Simulations' AND id > 178;
INSERT IGNORE INTO resource_tags (resource_id, tag) SELECT id, 'html5' FROM resources WHERE source_name = 'Physics Simulations' AND id > 178;
