<?php
// ================================================================
// api/og-image.php — Dynamic Open Graph Image Generator
//
// Strategy:
//   1. First: try to serve a real screenshot from /thumbnails/og-{id}.png
//      (generated by headless Chrome via generate-thumbnails.sh)
//   2. Fallback: generate a text-based card with PHP GD
//
// URL: /api/og-image.php?id={resource_id}
// Auth: None (public)
// ================================================================

$id = (int) ($_GET['id'] ?? 0);
if (!$id) {
    http_response_code(400);
    exit('Missing id');
}

// ── Strategy 1: Real screenshot thumbnail ────────────────────
$docRoot = $_SERVER['DOCUMENT_ROOT'] ?? dirname(__DIR__);
$thumbnailPath = rtrim($docRoot, '/') . '/thumbnails/og-' . $id . '.png';
if (file_exists($thumbnailPath)) {
    header('Content-Type: image/png');
    header('Cache-Control: public, max-age=86400');
    readfile($thumbnailPath);
    exit;
}

// ── Strategy 2: Generated text card (fallback) ───────────────
require_once __DIR__ . '/../shared/db.php';

$db = getResourcesDB();
$stmt = $db->prepare("
    SELECT r.title, r.description, r.subject_area, r.code_type,
           r.author_display_name, r.view_count, r.like_count, r.lang,
           r.level, r.source_name, c.name AS category_name
    FROM resources r
    LEFT JOIN categories c ON r.category_id = c.id
    WHERE r.id = ? AND r.is_active = 1 AND r.visibility = 'community'
");
$stmt->execute([$id]);
$r = $stmt->fetch();

if (!$r) {
    http_response_code(404);
    exit('Resource not found');
}

// ── Create image ─────────────────────────────────────────────
$w = 1200;
$h = 630;
$img = imagecreatetruecolor($w, $h);
imagealphablending($img, true);
imagesavealpha($img, true);

// Solid dark background
$bgColor = imagecolorallocate($img, 15, 23, 42);
imagefilledrectangle($img, 0, 0, $w, $h, $bgColor);

// Left accent bar (gradient purple→cyan)
for ($y = 0; $y < $h; $y++) {
    $ratio = $y / $h;
    $cr = (int) (124 + $ratio * (6 - 124));
    $cg = (int) (58 + $ratio * (182 - 58));
    $cb = (int) (237 + $ratio * (212 - 237));
    $barColor = imagecolorallocate($img, $cr, $cg, $cb);
    imagefilledrectangle($img, 0, $y, 8, $y, $barColor);
}

// Subtle background glow
$glow1 = imagecolorallocatealpha($img, 124, 58, 237, 115);
imagefilledellipse($img, $w - 100, 80, 500, 500, $glow1);
$glow2 = imagecolorallocatealpha($img, 6, 182, 212, 118);
imagefilledellipse($img, 200, $h - 50, 400, 400, $glow2);

// ── Fonts (fallback chain) ───────────────────────────────────
$fontCandidates = [
    'bold' => [
        '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
        '/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf',
        '/usr/share/fonts/google-droid/DroidSans-Bold.ttf',
        '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf',
        '/usr/share/fonts/dejavu/DejaVuSansMono-Bold.ttf',
    ],
    'regular' => [
        '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
        '/usr/share/fonts/dejavu/DejaVuSans.ttf',
        '/usr/share/fonts/google-droid/DroidSans.ttf',
        '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf',
        '/usr/share/fonts/dejavu/DejaVuSansMono.ttf',
    ],
];

$fontBold = $fontRegular = null;
foreach ($fontCandidates['bold'] as $path) {
    if (file_exists($path)) { $fontBold = $path; break; }
}
foreach ($fontCandidates['regular'] as $path) {
    if (file_exists($path)) { $fontRegular = $path; break; }
}
if (!$fontRegular) $fontRegular = $fontBold = '';
if (!$fontBold)    $fontBold = $fontRegular;

// Colors
$white     = imagecolorallocate($img, 255, 255, 255);
$lightGray = imagecolorallocate($img, 203, 213, 225);
$medGray   = imagecolorallocate($img, 148, 163, 184);
$purple    = imagecolorallocate($img, 167, 139, 250);
$cyan      = imagecolorallocate($img, 34, 211, 238);

$padL = 60;
$padR = 60;
$maxTextW = $w - $padL - $padR;

// ── Category pill ────────────────────────────────────────────
$area = $r['category_name'] ?? $r['subject_area'] ?? '';
$topY = 60;
if ($area) {
    $areaBbox = imagettfbbox(20, 0, $fontBold, $area);
    $areaPillW = $areaBbox[2] - $areaBbox[0] + 32;
    $pillBg = imagecolorallocatealpha($img, 6, 182, 212, 90);
    imagefilledrectangle($img, $padL, $topY, $padL + $areaPillW, $topY + 40, $pillBg);
    imagettftext($img, 20, 0, $padL + 16, $topY + 29, $white, $fontBold, $area);
    $topY += 60;
} else {
    $topY += 10;
}

// ── Title (BIG for mobile readability) ───────────────────────
$title = mb_substr($r['title'], 0, 70, 'UTF-8');
if (mb_strlen($r['title'], 'UTF-8') > 70) $title .= '...';

$titleLines = wrapText($title, $fontBold, 42, $maxTextW);
foreach ($titleLines as $i => $line) {
    if ($i >= 2) break;
    imagettftext($img, 42, 0, $padL, $topY + 50 + ($i * 58), $white, $fontBold, $line);
}
$titleBottomY = $topY + 50 + (min(count($titleLines), 2) * 58);

// ── Description ──────────────────────────────────────────────
if ($r['description']) {
    $desc = mb_substr($r['description'], 0, 100, 'UTF-8');
    if (mb_strlen($r['description'], 'UTF-8') > 100) $desc .= '...';

    $descLines = wrapText($desc, $fontRegular, 22, $maxTextW);
    $descY = $titleBottomY + 20;
    foreach ($descLines as $i => $line) {
        if ($i >= 2) break;
        imagettftext($img, 22, 0, $padL, $descY + ($i * 34), $lightGray, $fontRegular, $line);
    }
}

// ── Bottom bar ───────────────────────────────────────────────
$bottomY = $h - 80;
$sepColor = imagecolorallocatealpha($img, 148, 163, 184, 100);
imageline($img, $padL, $bottomY - 20, $w - $padR, $bottomY - 20, $sepColor);

// Branding + author
imagettftext($img, 24, 0, $padL, $bottomY + 8, $purple, $fontBold, 'iarepo');
if ($r['author_display_name']) {
    $brandBbox = imagettfbbox(24, 0, $fontBold, 'iarepo');
    $brandW = $brandBbox[2] - $brandBbox[0];
    imagettftext($img, 18, 0, $padL + $brandW + 12, $bottomY + 5, $medGray, $fontRegular, '  /  ' . $r['author_display_name']);
}

// Code type + lang badge
$typeText = strtoupper($r['code_type'] ?? 'HTML');
$langText = match($r['lang'] ?? '') { 'es' => 'ES', 'en' => 'EN', 'pt' => 'PT', default => '' };
$badgeText = $typeText . ($langText ? '  ' . $langText : '');
$badgeBbox = imagettfbbox(18, 0, $fontBold, $badgeText);
$badgeW = $badgeBbox[2] - $badgeBbox[0] + 28;
$badgeX = $w - $padR - $badgeW;
$badgeBg = imagecolorallocatealpha($img, 30, 41, 59, 40);
imagefilledrectangle($img, $badgeX, $bottomY - 12, $w - $padR, $bottomY + 18, $badgeBg);
imagettftext($img, 18, 0, $badgeX + 14, $bottomY + 10, $cyan, $fontBold, $badgeText);

// ── Output ───────────────────────────────────────────────────
header('Content-Type: image/png');
header('Cache-Control: public, max-age=3600');
imagepng($img, null, 6);
imagedestroy($img);
exit;


// ══════════════════════════════════════════════════════════════
function wrapText(string $text, string $font, int $fontSize, int $maxWidth): array {
    $words = explode(' ', $text);
    $lines = [];
    $currentLine = '';
    foreach ($words as $word) {
        $testLine = $currentLine ? $currentLine . ' ' . $word : $word;
        $bbox = imagettfbbox($fontSize, 0, $font, $testLine);
        if (($bbox[2] - $bbox[0]) > $maxWidth && $currentLine !== '') {
            $lines[] = $currentLine;
            $currentLine = $word;
        } else {
            $currentLine = $testLine;
        }
    }
    if ($currentLine !== '') $lines[] = $currentLine;
    return $lines;
}
